# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/benfiola/Documents/os_workspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/benfiola/Documents/os_workspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benfiola/Documents/os_workspace/CMakeFiles /home/benfiola/Documents/os_workspace/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benfiola/Documents/os_workspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named iso

# Build rule for target.
iso: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iso
.PHONY : iso

# fast build rule for target.
iso/fast:
	$(MAKE) -f CMakeFiles/iso.dir/build.make CMakeFiles/iso.dir/build
.PHONY : iso/fast

#=============================================================================
# Target rules for targets named qemu

# Build rule for target.
qemu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qemu
.PHONY : qemu

# fast build rule for target.
qemu/fast:
	$(MAKE) -f CMakeFiles/qemu.dir/build.make CMakeFiles/qemu.dir/build
.PHONY : qemu/fast

#=============================================================================
# Target rules for targets named kernel-includes

# Build rule for target.
kernel-includes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel-includes
.PHONY : kernel-includes

# fast build rule for target.
kernel-includes/fast:
	$(MAKE) -f kernel/include/CMakeFiles/kernel-includes.dir/build.make kernel/include/CMakeFiles/kernel-includes.dir/build
.PHONY : kernel-includes/fast

#=============================================================================
# Target rules for targets named libc-includes

# Build rule for target.
libc-includes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libc-includes
.PHONY : libc-includes

# fast build rule for target.
libc-includes/fast:
	$(MAKE) -f libc/include/CMakeFiles/libc-includes.dir/build.make libc/include/CMakeFiles/libc-includes.dir/build
.PHONY : libc-includes/fast

#=============================================================================
# Target rules for targets named clibs

# Build rule for target.
clibs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clibs
.PHONY : clibs

# fast build rule for target.
clibs/fast:
	$(MAKE) -f libc/CMakeFiles/clibs.dir/build.make libc/CMakeFiles/clibs.dir/build
.PHONY : clibs/fast

#=============================================================================
# Target rules for targets named clibs-deploy

# Build rule for target.
clibs-deploy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clibs-deploy
.PHONY : clibs-deploy

# fast build rule for target.
clibs-deploy/fast:
	$(MAKE) -f libc/CMakeFiles/clibs-deploy.dir/build.make libc/CMakeFiles/clibs-deploy.dir/build
.PHONY : clibs-deploy/fast

#=============================================================================
# Target rules for targets named libc

# Build rule for target.
libc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libc
.PHONY : libc

# fast build rule for target.
libc/fast:
	$(MAKE) -f libc/CMakeFiles/libc.dir/build.make libc/CMakeFiles/libc.dir/build
.PHONY : libc/fast

#=============================================================================
# Target rules for targets named libc-deploy

# Build rule for target.
libc-deploy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libc-deploy
.PHONY : libc-deploy

# fast build rule for target.
libc-deploy/fast:
	$(MAKE) -f libc/CMakeFiles/libc-deploy.dir/build.make libc/CMakeFiles/libc-deploy.dir/build
.PHONY : libc-deploy/fast

#=============================================================================
# Target rules for targets named libk

# Build rule for target.
libk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libk
.PHONY : libk

# fast build rule for target.
libk/fast:
	$(MAKE) -f libc/CMakeFiles/libk.dir/build.make libc/CMakeFiles/libk.dir/build
.PHONY : libk/fast

#=============================================================================
# Target rules for targets named libk-deploy

# Build rule for target.
libk-deploy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libk-deploy
.PHONY : libk-deploy

# fast build rule for target.
libk-deploy/fast:
	$(MAKE) -f libc/CMakeFiles/libk-deploy.dir/build.make libc/CMakeFiles/libk-deploy.dir/build
.PHONY : libk-deploy/fast

#=============================================================================
# Target rules for targets named crti

# Build rule for target.
crti: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crti
.PHONY : crti

# fast build rule for target.
crti/fast:
	$(MAKE) -f kernel/CMakeFiles/crti.dir/build.make kernel/CMakeFiles/crti.dir/build
.PHONY : crti/fast

#=============================================================================
# Target rules for targets named crtn

# Build rule for target.
crtn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crtn
.PHONY : crtn

# fast build rule for target.
crtn/fast:
	$(MAKE) -f kernel/CMakeFiles/crtn.dir/build.make kernel/CMakeFiles/crtn.dir/build
.PHONY : crtn/fast

#=============================================================================
# Target rules for targets named kernel

# Build rule for target.
kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kernel
.PHONY : kernel

# fast build rule for target.
kernel/fast:
	$(MAKE) -f kernel/CMakeFiles/kernel.dir/build.make kernel/CMakeFiles/kernel.dir/build
.PHONY : kernel/fast

#=============================================================================
# Target rules for targets named myos.kernel

# Build rule for target.
myos.kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myos.kernel
.PHONY : myos.kernel

# fast build rule for target.
myos.kernel/fast:
	$(MAKE) -f kernel/CMakeFiles/myos.kernel.dir/build.make kernel/CMakeFiles/myos.kernel.dir/build
.PHONY : myos.kernel/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... qemu"
	@echo "... iso"
	@echo "... edit_cache"
	@echo "... clean-all"
	@echo "... kernel-includes"
	@echo "... libc-includes"
	@echo "... clibs-deploy"
	@echo "... libk-deploy"
	@echo "... libc-deploy"
	@echo "... libk"
	@echo "... clibs"
	@echo "... libc"
	@echo "... myos.kernel"
	@echo "... kernel"
	@echo "... crtn"
	@echo "... crti"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

